# Site settings
author: Jessie Rohrer
title: Code Well
header-img: img/home-bg.png
email: jessie.rohrer@gmail.com
copyright_name: Jessie Rohrer
description: > # this means to ignore newlines until "baseurl:"
  Changing things by learning to code well.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jrrohrer

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
